export type BoiSeriesDefinition =
  {
      kind: "sdmx";
      key: string;
      label: string;
      category: string;
      unit: string | null;
      agencyId: string;
      dataflowId: string;
      version: string;
      structureId?: string;
      seriesCode: string;
      startPeriod: string;
      queryKey?: string;
      transform?: (value: number) => number;
      aggregate?: "month-end";
    };

export const BOI_SERIES_DEFINITIONS: BoiSeriesDefinition[] = [
  {
    kind: "sdmx",
    key: "policy_rate",
    label: "ריבית בנק ישראל",
    category: "מוניטרי",
    unit: "%",
    agencyId: "BOI.STATISTICS",
    dataflowId: "BR",
    version: "1.0",
    seriesCode: "MNT_RIB_BOI_D",
    startPeriod: "2016-01",
    aggregate: "month-end",
  },
  {
    kind: "sdmx",
    key: "cpi_monthly_change",
    label: "שינוי חודשי במדד המחירים לצרכן",
    category: "מחירים",
    unit: "%",
    agencyId: "BOI.STATISTICS",
    dataflowId: "PRI",
    version: "1.0",
    seriesCode: "CP_PCH",
    startPeriod: "2024-01",
  },
  {
    kind: "sdmx",
    key: "inflation_expectations_1y",
    label: "ציפיות אינפלציה לשנה קדימה",
    category: "מחירים",
    unit: "%",
    agencyId: "BOI.STATISTICS",
    dataflowId: "ZCM",
    version: "1.0",
    seriesCode: "EXP_EXP_01Y_BI_MA",
    startPeriod: "2024-01",
  },
  {
    kind: "sdmx",
    key: "monthly_activity_index",
    label: "מדד הפעילות הכלכלית החודשי",
    category: "צמיחה",
    unit: "נק'",
    agencyId: "BOI.STATISTICS",
    dataflowId: "ECON_IND",
    version: "1.0",
    seriesCode: "BOI_EAI_M",
    startPeriod: "2024-01",
  },
  {
    kind: "sdmx",
    key: "monthly_activity_index_3m_avg",
    label: "מדד הפעילות הכלכלית החודשי, ממוצע נע 3 חודשים",
    category: "צמיחה",
    unit: "נק'",
    agencyId: "BOI.STATISTICS",
    dataflowId: "ECON_IND",
    version: "1.0",
    seriesCode: "BOI_EAI_MVAVG3_M",
    startPeriod: "2024-01",
  },
  {
    kind: "sdmx",
    key: "unemployment_rate",
    label: "שיעור האבטלה",
    category: "שוק העבודה",
    unit: "%",
    agencyId: "BOI.STATISTICS",
    dataflowId: "LBM",
    version: "1.0",
    seriesCode: "UE_R_M_SA",
    startPeriod: "2024-01",
  },
  {
    kind: "sdmx",
    key: "real_wages",
    label: "שכר ריאלי ממוצע",
    category: "שוק העבודה",
    unit: 'ש"ח',
    agencyId: "BOI.STATISTICS",
    dataflowId: "LBM",
    version: "1.0",
    seriesCode: "RW_M_CHAINED",
    startPeriod: "2024-01",
  },
  {
    kind: "sdmx",
    key: "usd_ils",
    label: 'דולר / ש"ח',
    category: 'מט"ח',
    unit: 'ש"ח',
    agencyId: "BOI.STATISTICS",
    dataflowId: "EXR",
    version: "1.0",
    seriesCode: "RER_USD_ILS",
    startPeriod: "2025-01",
    aggregate: "month-end",
  },
  {
    kind: "sdmx",
    key: "current_account_pct_gdp",
    label: "חשבון שוטף כאחוז מהתוצר",
    category: "מגזר חיצוני",
    unit: "%",
    agencyId: "BOI.STATISTICS",
    dataflowId: "BOP",
    version: "1.0",
    seriesCode: "BOP_NC1000N3_GDP_R_Q",
    startPeriod: "2024-01",
  },
  {
    kind: "sdmx",
    key: "fx_reserves_usd",
    label: 'יתרות מט"ח',
    category: "מגזר חיצוני",
    unit: "מיליארד דולר",
    agencyId: "BOI.STATISTICS",
    dataflowId: "ACC",
    version: "1.0",
    seriesCode: "ACC_RES2700018_D_B_ME",
    startPeriod: "2024-01",
    transform: (value) => value / 1_000,
  },
  {
    kind: "sdmx",
    key: "housing_credit_total",
    label: "אשראי לדיור",
    category: "אשראי לדיור",
    unit: 'מיליארד ש"ח',
    agencyId: "BOI.STATISTICS",
    dataflowId: "BFR_99",
    structureId: "BFR",
    version: "1.0",
    seriesCode: "BNK_99910_FR_FINREP_268",
    startPeriod: "2024-01",
    transform: (value) => value / 1_000_000,
  },
  {
    kind: "sdmx",
    key: "rent_index",
    label: "מדד שכר דירה",
    category: "מחירים",
    unit: "נק'",
    agencyId: "BOI.STATISTICS",
    dataflowId: "PRI",
    version: "1.0",
    seriesCode: "CP020100",
    startPeriod: "2024-01",
  },
  {
    kind: "sdmx",
    key: "new_mortgage_rate",
    label: "ריבית ממוצעת על משכנתאות חדשות",
    category: "מימון דיור",
    unit: "%",
    agencyId: "BOI.STATISTICS",
    dataflowId: "BIR_MRTG_99",
    structureId: "BIR_MRTG",
    version: "1.0",
    seriesCode: "BNK_99034_LR_BIR_MRTG_462",
    startPeriod: "2024-01",
  },
  {
    kind: "sdmx",
    key: "new_mortgage_volume",
    label: "היקף משכנתאות חדשות",
    category: "מימון דיור",
    unit: 'מיליארד ש"ח',
    agencyId: "BOI.STATISTICS",
    dataflowId: "BIR_MRTG_99",
    structureId: "BIR_MRTG",
    version: "1.0",
    seriesCode: "BNK_99034_LR_BIR_MRTG_897",
    startPeriod: "2024-01",
    transform: (value) => value / 1_000_000,
  },
  {
    kind: "sdmx",
    key: "gov_bond_yield_10y",
    label: "תשואת אג״ח ממשלתי ל-10 שנים",
    category: "שוק ההון",
    unit: "%",
    agencyId: "BOI.STATISTICS",
    dataflowId: "ZCM",
    version: "1.0",
    seriesCode: "ZC_TSB_ZND_10Y_MA",
    startPeriod: "2024-01",
  },
  {
    kind: "sdmx",
    key: "gov_deficit_monthly",
    label: "גירעון ממשלתי חודשי",
    category: "פיסקלי",
    unit: 'מיליון ש"ח',
    agencyId: "BOI.STATISTICS",
    dataflowId: "PS",
    version: "1.0",
    seriesCode: "OZAR_A5TZM_M",
    startPeriod: "2024-01",
  },
  {
    kind: "sdmx",
    key: "m1_money_supply",
    label: "היצע כסף M1",
    category: "מוניטרי",
    unit: 'מיליון ש"ח',
    agencyId: "BOI.STATISTICS",
    dataflowId: "MAG",
    version: "1.0",
    seriesCode: "MAG_M1_SA_M",
    startPeriod: "2024-01",
  },
  {
    kind: "sdmx",
    key: "construction_cost_index",
    label: "מדד תשומות הבנייה",
    category: "עלויות בנייה",
    unit: "נק'",
    agencyId: "BOI.STATISTICS",
    dataflowId: "PRI",
    version: "1.0",
    seriesCode: "BIP",
    startPeriod: "2024-01",
  },
  {
    kind: "sdmx",
    key: "neer",
    label: "שער חליפין אפקטיבי נומינלי",
    category: 'מט"ח',
    unit: "נק'",
    agencyId: "BOI.STATISTICS",
    dataflowId: "EXR",
    version: "1.0",
    seriesCode: "NER_ILS_BSK_IDX",
    startPeriod: "2024-01",
  },
  {
    kind: "sdmx",
    key: "gdp_growth",
    label: "צמיחת תוצר לנפש",
    category: "צמיחה",
    unit: "%",
    agencyId: "BOI.STATISTICS",
    dataflowId: "NA",
    version: "1.0",
    seriesCode: "BI_PCT_GDP_PER_CAPITA_Q_FP_SA",
    startPeriod: "2024-01",
  },
];
